### ISSUE TITLE
icon proposals

### ISSUE THREAD

**Issue by haggen88** [linuxmint/jargonaut#1]
HI @clefebvre, maybe this can help:   

![0a](https://github.com/linuxmint/jargonaut/assets/68134588/c5199097-538e-4acc-a3ce-40756d3b8077)
![3](https://github.com/linuxmint/jargonaut/assets/68134588/01ca2be4-d250-498d-be76-0fed5f458df9)
![agaga](https://github.com/linuxmint/jargonaut/assets/68134588/a929c3be-eabd-4216-a90c-d16c893429fb)
![654](https://github.com/linuxmint/jargonaut/assets/68134588/61546c0c-acf6-47ce-94f5-b523bb4d7ae0)

- [jargonaut.icon.draft_.zip](https://github.com/linuxmint/jargonaut/files/14746174/jargonaut.icon.draft_.zip)
- [jargonaut-symbolic.svg.zip](https://github.com/linuxmint/jargonaut/files/14525319/jargonaut-symbolic.svg.zip)

(***updated**)

I guess when HexChat is discontinued this app will take its place in the future, right?

**Comment by haggen88** [comment]
Other options : [jargonaut.icon.draft_2.zip](https://github.com/linuxmint/jargonaut/files/14469504/jargonaut.icon.draft_2.zip)

**Comment by IfGremlinThen** [comment]
Just a letter in a speech bubble looks plain and boring.  Why not go off the _-naut_ part and incorporate an astronaut or dive suit (aquanaut) helmet?

**Comment by haggen88** [comment]
I just opted for a simpler icon that makes it easier to understand the functionality of the app.
