### ISSUE TITLE
Should the name still be considered something else? "Jargonaut" does not imply anything to new comers | Help Chat?

### ISSUE THREAD

**Issue by vrement** [linuxmint/jargonaut#2]
So if the idea is to have a support and help chat for Linux Mint and be clicked on the program menu quickly towards help, should the name be something akin to Mint Chat or Linux Mint Support Chat or something along those lines? 

If i understood correctly, Jargonaut is not even supposed to be or appear as a full fledged IRC client but only built on the IRC foundation. 

This was the first thing that popped to my mind when seeing the name "Jargonaut". The connection to "jargon" still does not suffice IMO (if that's even the point related to talking).

**Comment by carlosmintfan** [comment]
https://github.com/linuxmint/jargonaut shows "Chat room" as name. I think Jargonaut is more an internal name, not the one displayed to users in the startmenu. That's true for other mint apps like Nemo and Bulky too.

**Comment by carlosmintfan** [comment]
Oops, the right link is https://github.com/linuxmint/jargonaut/blob/master/data/jargonaut.desktop.in

**Comment by vrement** [comment]
> https://github.com/linuxmint/jargonaut shows "Chat room" as name. I think Jargonaut is more an internal name, not the one displayed to users in the startmenu. That's true for other mint apps like Nemo and Bulky too.

Nice ok, that's very good! (and kinda relief phew) :D

**Comment by carlosmintfan** [comment]
@vrement I think you could close this issue now :) (I can't do that because I'm not a mint team member...)
